# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Alca < Formula
  desc "Run code agents unrestricted, but fearlessly"
  homepage "https://github.com/bolasblack/alcatraz"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/bolasblack/alcatraz/releases/download/v0.1.0/alcatraz_0.1.0_darwin_amd64.tar.gz"
      sha256 "44bc4df6488d3214f6c20d1a89bb3e57a41d3ed62f72bed0d3934563ffe20898"

      def install
        bin.install "alca"
        man1.install Dir["man/man1/*"]
        bash_completion.install "completions/alca.bash" => "alca"
        zsh_completion.install "completions/alca.zsh" => "_alca"
        fish_completion.install "completions/alca.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/bolasblack/alcatraz/releases/download/v0.1.0/alcatraz_0.1.0_darwin_arm64.tar.gz"
      sha256 "ea729458b0dd65b18e8205289edb74fc635ecae01d1eedec742d80b062a56709"

      def install
        bin.install "alca"
        man1.install Dir["man/man1/*"]
        bash_completion.install "completions/alca.bash" => "alca"
        zsh_completion.install "completions/alca.zsh" => "_alca"
        fish_completion.install "completions/alca.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/bolasblack/alcatraz/releases/download/v0.1.0/alcatraz_0.1.0_linux_amd64.tar.gz"
      sha256 "2ebb93ada6422ae2261685def4c7fb2bc71d20704bfbb48777bdb29e69e6980b"
      def install
        bin.install "alca"
        man1.install Dir["man/man1/*"]
        bash_completion.install "completions/alca.bash" => "alca"
        zsh_completion.install "completions/alca.zsh" => "_alca"
        fish_completion.install "completions/alca.fish"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/bolasblack/alcatraz/releases/download/v0.1.0/alcatraz_0.1.0_linux_arm64.tar.gz"
      sha256 "612294e884866eb18a097cf1ae7ff4c057a87ce71b94963b0b986b9f14ee6bcc"
      def install
        bin.install "alca"
        man1.install Dir["man/man1/*"]
        bash_completion.install "completions/alca.bash" => "alca"
        zsh_completion.install "completions/alca.zsh" => "_alca"
        fish_completion.install "completions/alca.fish"
      end
    end
  end

  test do
    system "#{bin}/alca", "--version"
  end
end
