# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Alca < Formula
  desc "Run code agents unrestricted, but fearlessly"
  homepage "https://github.com/bolasblack/alcatraz"
  version "0.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/bolasblack/alcatraz/releases/download/v0.3.0/alcatraz_0.3.0_darwin_amd64.tar.gz"
      sha256 "f354d0530c4c3f6179b2ee18d7cf7d4963e7a0eab8814c318bebeadc22e19a3f"

      define_method(:install) do
        bin.install "alca"
        man1.install Dir["man/man1/*"]
        bash_completion.install "completions/alca.bash" => "alca"
        zsh_completion.install "completions/alca.zsh" => "_alca"
        fish_completion.install "completions/alca.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/bolasblack/alcatraz/releases/download/v0.3.0/alcatraz_0.3.0_darwin_arm64.tar.gz"
      sha256 "8bdb7bc07287f39efb6623122c6213674e1e47994f0cd8fa44b3f885c0dce792"

      define_method(:install) do
        bin.install "alca"
        man1.install Dir["man/man1/*"]
        bash_completion.install "completions/alca.bash" => "alca"
        zsh_completion.install "completions/alca.zsh" => "_alca"
        fish_completion.install "completions/alca.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/bolasblack/alcatraz/releases/download/v0.3.0/alcatraz_0.3.0_linux_amd64.tar.gz"
      sha256 "4ffb00a8d9c15ad618e1146829105a4556b7b11e61986434ba8e07704618b5c9"
      define_method(:install) do
        bin.install "alca"
        man1.install Dir["man/man1/*"]
        bash_completion.install "completions/alca.bash" => "alca"
        zsh_completion.install "completions/alca.zsh" => "_alca"
        fish_completion.install "completions/alca.fish"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/bolasblack/alcatraz/releases/download/v0.3.0/alcatraz_0.3.0_linux_arm64.tar.gz"
      sha256 "4ff7485f437549f0c4b9d06d2f152a29ac9f143f273f1b50ed93ec77a69a3f3f"
      define_method(:install) do
        bin.install "alca"
        man1.install Dir["man/man1/*"]
        bash_completion.install "completions/alca.bash" => "alca"
        zsh_completion.install "completions/alca.zsh" => "_alca"
        fish_completion.install "completions/alca.fish"
      end
    end
  end

  test do
    system "#{bin}/alca", "--version"
  end
end
