# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Alca < Formula
  desc "Run code agents unrestricted, but fearlessly"
  homepage "https://github.com/bolasblack/alcatraz"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/bolasblack/alcatraz/releases/download/v0.2.0/alcatraz_0.2.0_darwin_amd64.tar.gz"
      sha256 "2df4f84a7c8349939749276badd15d5f72cff67d19dae982ba375a7a86ef9892"

      define_method(:install) do
        bin.install "alca"
        man1.install Dir["man/man1/*"]
        bash_completion.install "completions/alca.bash" => "alca"
        zsh_completion.install "completions/alca.zsh" => "_alca"
        fish_completion.install "completions/alca.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/bolasblack/alcatraz/releases/download/v0.2.0/alcatraz_0.2.0_darwin_arm64.tar.gz"
      sha256 "c221fcfa4bffffacda2961abee30ce219eb3d78c7a3e01454bd0bd61e99c3d80"

      define_method(:install) do
        bin.install "alca"
        man1.install Dir["man/man1/*"]
        bash_completion.install "completions/alca.bash" => "alca"
        zsh_completion.install "completions/alca.zsh" => "_alca"
        fish_completion.install "completions/alca.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/bolasblack/alcatraz/releases/download/v0.2.0/alcatraz_0.2.0_linux_amd64.tar.gz"
      sha256 "84df7763789300899f0423ea78203506fc0d308342edfb35310f0a24c099b12f"
      define_method(:install) do
        bin.install "alca"
        man1.install Dir["man/man1/*"]
        bash_completion.install "completions/alca.bash" => "alca"
        zsh_completion.install "completions/alca.zsh" => "_alca"
        fish_completion.install "completions/alca.fish"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/bolasblack/alcatraz/releases/download/v0.2.0/alcatraz_0.2.0_linux_arm64.tar.gz"
      sha256 "397ef5a7460a60853e851463e1bc0b060af4705b000fede2beefd6fa5f1281cf"
      define_method(:install) do
        bin.install "alca"
        man1.install Dir["man/man1/*"]
        bash_completion.install "completions/alca.bash" => "alca"
        zsh_completion.install "completions/alca.zsh" => "_alca"
        fish_completion.install "completions/alca.fish"
      end
    end
  end

  test do
    system "#{bin}/alca", "--version"
  end
end
