#:schema ./alca-config.schema.jsonc
# llms.txt: https://bolasblack.github.io/alcatraz/llms.txt

includes = ['./.alca.*.toml']
image = "nixos/nix"

workdir_exclude = [
  ".alca.mounts",
  "out",
  "out_*",
  "vendor",
  "result",
]

mounts = [
  ".alca.mounts/go:/root/go",
  ".alca.mounts/mise:/root/.local/share/mise",
  '.alca.mounts/extra-bin:/extra-bin',
  '.alca.mounts/extra-scripts:/extra-scripts'
]

[commands]
up = "[ -f flake.nix ] && exec nix develop --profile /nix/var/nix/profiles/devshell --command true"
enter = "[ -f flake.nix ] && exec nix develop --profile /nix/var/nix/profiles/devshell --command"

[resources]
memory = "16g"
cpus = 8

[envs]
IS_SANDBOX = "1"
NIXPKGS_ALLOW_UNFREE = "1"
NIX_CONFIG = """
extra-experimental-features = nix-command flakes
"""
